#############################################################################
# Makefile for building: project2-NFL.app/Contents/MacOS/project2-NFL
# Generated by qmake (3.1) (Qt 5.11.1)
# Project:  project2-NFL.pro
# Template: app
# Command: /Users/JoseCardenas/qt/5.11.1/clang_64/bin/qmake -o Makefile project2-NFL.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.11 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers -I../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers -I../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers -I../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../qt/5.11.1/clang_64/mkspecs/macx-clang -F/Users/JoseCardenas/qt/5.11.1/clang_64/lib
QMAKE         = /Users/JoseCardenas/qt/5.11.1/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/JoseCardenas/qt/5.11.1/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/JoseCardenas/qt/5.11.1/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = project2-NFL1.0.0
DISTDIR = /Users/JoseCardenas/nfl_project/project_2_NFL_jdaddy/.tmp/project2-NFL1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.11 -Wl,-rpath,@executable_path/Frameworks -Wl,-rpath,/Users/JoseCardenas/qt/5.11.1/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/JoseCardenas/qt/5.11.1/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtSql -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		adminwindow.cpp \
		dbmanager.cpp \
		adminbackend.cpp \
		team.cpp \
		stadium.cpp \
		makeoutputmodel.cpp \
		graph.cpp \
		summarywindow.cpp \
		souvenirmap.cpp \
		traversalsummarywindow.cpp \
		purchasewindow.cpp qrc_resource.cpp \
		moc_mainwindow.cpp \
		moc_adminwindow.cpp \
		moc_summarywindow.cpp \
		moc_traversalsummarywindow.cpp \
		moc_purchasewindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		adminwindow.o \
		dbmanager.o \
		adminbackend.o \
		team.o \
		stadium.o \
		makeoutputmodel.o \
		graph.o \
		summarywindow.o \
		souvenirmap.o \
		traversalsummarywindow.o \
		purchasewindow.o \
		qrc_resource.o \
		moc_mainwindow.o \
		moc_adminwindow.o \
		moc_summarywindow.o \
		moc_traversalsummarywindow.o \
		moc_purchasewindow.o
DIST          = ../../qt/5.11.1/clang_64/mkspecs/features/spec_pre.prf \
		../../qt/5.11.1/clang_64/mkspecs/qdevice.pri \
		../../qt/5.11.1/clang_64/mkspecs/features/device_config.prf \
		../../qt/5.11.1/clang_64/mkspecs/common/unix.conf \
		../../qt/5.11.1/clang_64/mkspecs/common/mac.conf \
		../../qt/5.11.1/clang_64/mkspecs/common/macx.conf \
		../../qt/5.11.1/clang_64/mkspecs/common/sanitize.conf \
		../../qt/5.11.1/clang_64/mkspecs/common/gcc-base.conf \
		../../qt/5.11.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../qt/5.11.1/clang_64/mkspecs/common/clang.conf \
		../../qt/5.11.1/clang_64/mkspecs/common/clang-mac.conf \
		../../qt/5.11.1/clang_64/mkspecs/qconfig.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/features/qt_functions.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/qt_config.prf \
		../../qt/5.11.1/clang_64/mkspecs/macx-clang/qmake.conf \
		../../qt/5.11.1/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../qt/5.11.1/clang_64/mkspecs/features/exclusive_builds.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/mac/sdk.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/toolchain.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/mac/toolchain.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/default_pre.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/mac/default_pre.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/resolve_config.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/default_post.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/mac/default_post.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/mac/objective_c.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/qml_debug.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/mac/mac.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/warn_on.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/qt.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/resources.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/moc.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/unix/opengl.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/uic.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/unix/thread.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/qmake_use.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/file_copies.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/mac/rez.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/testcase_targets.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/exceptions.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/yacc.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/lex.prf \
		project2-NFL.pro mainwindow.h \
		adminwindow.h \
		dbmanager.h \
		adminbackend.h \
		team.h \
		stadium.h \
		makeoutputmodel.h \
		graph.h \
		summarywindow.h \
		souvenirmap.h \
		traversalsummarywindow.h \
		purchasewindow.h main.cpp \
		mainwindow.cpp \
		adminwindow.cpp \
		dbmanager.cpp \
		adminbackend.cpp \
		team.cpp \
		stadium.cpp \
		makeoutputmodel.cpp \
		graph.cpp \
		summarywindow.cpp \
		souvenirmap.cpp \
		traversalsummarywindow.cpp \
		purchasewindow.cpp
QMAKE_TARGET  = project2-NFL
DESTDIR       = 
TARGET        = project2-NFL.app/Contents/MacOS/project2-NFL

####### Custom Variables
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))


first: all
####### Build rules

$(TARGET): ui_mainwindow.h ui_adminwindow.h ui_summarywindow.h ui_traversalsummarywindow.h ui_purchasewindow.h $(OBJECTS)  
	@test -d project2-NFL.app/Contents/MacOS/ || mkdir -p project2-NFL.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: project2-NFL.pro ../../qt/5.11.1/clang_64/mkspecs/macx-clang/qmake.conf ../../qt/5.11.1/clang_64/mkspecs/features/spec_pre.prf \
		../../qt/5.11.1/clang_64/mkspecs/qdevice.pri \
		../../qt/5.11.1/clang_64/mkspecs/features/device_config.prf \
		../../qt/5.11.1/clang_64/mkspecs/common/unix.conf \
		../../qt/5.11.1/clang_64/mkspecs/common/mac.conf \
		../../qt/5.11.1/clang_64/mkspecs/common/macx.conf \
		../../qt/5.11.1/clang_64/mkspecs/common/sanitize.conf \
		../../qt/5.11.1/clang_64/mkspecs/common/gcc-base.conf \
		../../qt/5.11.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../qt/5.11.1/clang_64/mkspecs/common/clang.conf \
		../../qt/5.11.1/clang_64/mkspecs/common/clang-mac.conf \
		../../qt/5.11.1/clang_64/mkspecs/qconfig.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../qt/5.11.1/clang_64/mkspecs/features/qt_functions.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/qt_config.prf \
		../../qt/5.11.1/clang_64/mkspecs/macx-clang/qmake.conf \
		../../qt/5.11.1/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../qt/5.11.1/clang_64/mkspecs/features/exclusive_builds.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/mac/sdk.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/toolchain.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/mac/toolchain.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/default_pre.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/mac/default_pre.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/resolve_config.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/default_post.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/mac/default_post.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/mac/objective_c.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/qml_debug.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/mac/mac.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/warn_on.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/qt.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/resources.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/moc.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/unix/opengl.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/uic.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/unix/thread.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/qmake_use.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/file_copies.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/mac/rez.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/testcase_targets.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/exceptions.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/yacc.prf \
		../../qt/5.11.1/clang_64/mkspecs/features/lex.prf \
		project2-NFL.pro \
		resource.qrc \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/QtGui.prl \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/QtSql.prl \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile project2-NFL.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
../../qt/5.11.1/clang_64/mkspecs/features/spec_pre.prf:
../../qt/5.11.1/clang_64/mkspecs/qdevice.pri:
../../qt/5.11.1/clang_64/mkspecs/features/device_config.prf:
../../qt/5.11.1/clang_64/mkspecs/common/unix.conf:
../../qt/5.11.1/clang_64/mkspecs/common/mac.conf:
../../qt/5.11.1/clang_64/mkspecs/common/macx.conf:
../../qt/5.11.1/clang_64/mkspecs/common/sanitize.conf:
../../qt/5.11.1/clang_64/mkspecs/common/gcc-base.conf:
../../qt/5.11.1/clang_64/mkspecs/common/gcc-base-mac.conf:
../../qt/5.11.1/clang_64/mkspecs/common/clang.conf:
../../qt/5.11.1/clang_64/mkspecs/common/clang-mac.conf:
../../qt/5.11.1/clang_64/mkspecs/qconfig.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_core.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_help.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_location.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_network.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_repparser.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_script.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../qt/5.11.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../qt/5.11.1/clang_64/mkspecs/features/qt_functions.prf:
../../qt/5.11.1/clang_64/mkspecs/features/qt_config.prf:
../../qt/5.11.1/clang_64/mkspecs/macx-clang/qmake.conf:
../../qt/5.11.1/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../qt/5.11.1/clang_64/mkspecs/features/exclusive_builds.prf:
../../qt/5.11.1/clang_64/mkspecs/features/mac/sdk.prf:
../../qt/5.11.1/clang_64/mkspecs/features/toolchain.prf:
../../qt/5.11.1/clang_64/mkspecs/features/mac/toolchain.prf:
../../qt/5.11.1/clang_64/mkspecs/features/default_pre.prf:
../../qt/5.11.1/clang_64/mkspecs/features/mac/default_pre.prf:
../../qt/5.11.1/clang_64/mkspecs/features/resolve_config.prf:
../../qt/5.11.1/clang_64/mkspecs/features/default_post.prf:
../../qt/5.11.1/clang_64/mkspecs/features/mac/default_post.prf:
../../qt/5.11.1/clang_64/mkspecs/features/mac/objective_c.prf:
../../qt/5.11.1/clang_64/mkspecs/features/qml_debug.prf:
../../qt/5.11.1/clang_64/mkspecs/features/mac/mac.prf:
../../qt/5.11.1/clang_64/mkspecs/features/warn_on.prf:
../../qt/5.11.1/clang_64/mkspecs/features/qt.prf:
../../qt/5.11.1/clang_64/mkspecs/features/resources.prf:
../../qt/5.11.1/clang_64/mkspecs/features/moc.prf:
../../qt/5.11.1/clang_64/mkspecs/features/unix/opengl.prf:
../../qt/5.11.1/clang_64/mkspecs/features/uic.prf:
../../qt/5.11.1/clang_64/mkspecs/features/unix/thread.prf:
../../qt/5.11.1/clang_64/mkspecs/features/qmake_use.prf:
../../qt/5.11.1/clang_64/mkspecs/features/file_copies.prf:
../../qt/5.11.1/clang_64/mkspecs/features/mac/rez.prf:
../../qt/5.11.1/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../qt/5.11.1/clang_64/mkspecs/features/testcase_targets.prf:
../../qt/5.11.1/clang_64/mkspecs/features/exceptions.prf:
../../qt/5.11.1/clang_64/mkspecs/features/yacc.prf:
../../qt/5.11.1/clang_64/mkspecs/features/lex.prf:
project2-NFL.pro:
resource.qrc:
../../qt/5.11.1/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../qt/5.11.1/clang_64/lib/QtGui.framework/QtGui.prl:
../../qt/5.11.1/clang_64/lib/QtSql.framework/QtSql.prl:
../../qt/5.11.1/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile project2-NFL.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE

project2-NFL.app/Contents/PkgInfo: 
	@test -d project2-NFL.app/Contents || mkdir -p project2-NFL.app/Contents
	@$(DEL_FILE) project2-NFL.app/Contents/PkgInfo
	@echo "APPL????" > project2-NFL.app/Contents/PkgInfo
project2-NFL.app/Contents/Resources/empty.lproj: 
	@test -d project2-NFL.app/Contents/Resources || mkdir -p project2-NFL.app/Contents/Resources
	@touch project2-NFL.app/Contents/Resources/empty.lproj
	
project2-NFL.app/Contents/Info.plist: 
	@test -d project2-NFL.app/Contents || mkdir -p project2-NFL.app/Contents
	@$(DEL_FILE) project2-NFL.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.project2-NFL,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.project2-NFL,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.11,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,project2-NFL,g" -e "s,@LIBRARY@,project2-NFL,g" -e "s,\$${EXECUTABLE_NAME},project2-NFL,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" ../../qt/5.11.1/clang_64/mkspecs/macx-clang/Info.plist.app >project2-NFL.app/Contents/Info.plist

all: Makefile \
		project2-NFL.app/Contents/PkgInfo \
		project2-NFL.app/Contents/Resources/empty.lproj \
		project2-NFL.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resource.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../../qt/5.11.1/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h adminwindow.h dbmanager.h adminbackend.h team.h stadium.h makeoutputmodel.h graph.h summarywindow.h souvenirmap.h traversalsummarywindow.h purchasewindow.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp adminwindow.cpp dbmanager.cpp adminbackend.cpp team.cpp stadium.cpp makeoutputmodel.cpp graph.cpp summarywindow.cpp souvenirmap.cpp traversalsummarywindow.cpp purchasewindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui adminwindow.ui summarywindow.ui traversalsummarywindow.ui purchasewindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r project2-NFL.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resource.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resource.cpp
qrc_resource.cpp: resource.qrc \
		../../qt/5.11.1/clang_64/bin/rcc \
		ExtendedTeam.txt \
		Pictures/admin6.jpg \
		Pictures/summaryDisplay1.png \
		Pictures/GraphWithSanDiego.PNG \
		Pictures/admin4.jpg \
		Pictures/GraphWithoutSanDiego.PNG \
		Pictures/purchaseWindow6.jpeg \
		Pictures/mainWindow_bkg.png
	/Users/JoseCardenas/qt/5.11.1/clang_64/bin/rcc -name resource resource.qrc -o qrc_resource.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../qt/5.11.1/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.11 -Wall -W -dM -E -o moc_predefs.h ../../qt/5.11.1/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_adminwindow.cpp moc_summarywindow.cpp moc_traversalsummarywindow.cpp moc_purchasewindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_adminwindow.cpp moc_summarywindow.cpp moc_traversalsummarywindow.cpp moc_purchasewindow.cpp
moc_mainwindow.cpp: ../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		adminbackend.h \
		dbmanager.h \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QDir \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QString \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QFile \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/QtSql \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qtsqlglobal.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QVector \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qvector.h \
		team.h \
		stadium.h \
		makeoutputmodel.h \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/QStandardItemModel \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		souvenirmap.h \
		adminwindow.h \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QListWidgetItem \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qlistwidget.h \
		traversalsummarywindow.h \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		summarywindow.h \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/QPixmap \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		graph.h \
		purchasewindow.h \
		mainwindow.h \
		moc_predefs.h \
		../../qt/5.11.1/clang_64/bin/moc
	/Users/JoseCardenas/qt/5.11.1/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/JoseCardenas/qt/5.11.1/clang_64/mkspecs/macx-clang -I/Users/JoseCardenas/nfl_project/project_2_NFL_jdaddy -I/Users/JoseCardenas/qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/JoseCardenas/qt/5.11.1/clang_64/lib/QtGui.framework/Headers -I/Users/JoseCardenas/qt/5.11.1/clang_64/lib/QtSql.framework/Headers -I/Users/JoseCardenas/qt/5.11.1/clang_64/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward -F/Users/JoseCardenas/qt/5.11.1/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

moc_adminwindow.cpp: ../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		makeoutputmodel.h \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/QStandardItemModel \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		stadium.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QString \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qstring.h \
		team.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		souvenirmap.h \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QListWidgetItem \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qlistwidget.h \
		adminwindow.h \
		moc_predefs.h \
		../../qt/5.11.1/clang_64/bin/moc
	/Users/JoseCardenas/qt/5.11.1/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/JoseCardenas/qt/5.11.1/clang_64/mkspecs/macx-clang -I/Users/JoseCardenas/nfl_project/project_2_NFL_jdaddy -I/Users/JoseCardenas/qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/JoseCardenas/qt/5.11.1/clang_64/lib/QtGui.framework/Headers -I/Users/JoseCardenas/qt/5.11.1/clang_64/lib/QtSql.framework/Headers -I/Users/JoseCardenas/qt/5.11.1/clang_64/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward -F/Users/JoseCardenas/qt/5.11.1/clang_64/lib adminwindow.h -o moc_adminwindow.cpp

moc_summarywindow.cpp: ../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/QPixmap \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		dbmanager.h \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QDir \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QString \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QFile \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/QtSql \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qtsqlglobal.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QVector \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qvector.h \
		team.h \
		stadium.h \
		summarywindow.h \
		moc_predefs.h \
		../../qt/5.11.1/clang_64/bin/moc
	/Users/JoseCardenas/qt/5.11.1/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/JoseCardenas/qt/5.11.1/clang_64/mkspecs/macx-clang -I/Users/JoseCardenas/nfl_project/project_2_NFL_jdaddy -I/Users/JoseCardenas/qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/JoseCardenas/qt/5.11.1/clang_64/lib/QtGui.framework/Headers -I/Users/JoseCardenas/qt/5.11.1/clang_64/lib/QtSql.framework/Headers -I/Users/JoseCardenas/qt/5.11.1/clang_64/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward -F/Users/JoseCardenas/qt/5.11.1/clang_64/lib summarywindow.h -o moc_summarywindow.cpp

moc_traversalsummarywindow.cpp: ../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/QStandardItemModel \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		traversalsummarywindow.h \
		moc_predefs.h \
		../../qt/5.11.1/clang_64/bin/moc
	/Users/JoseCardenas/qt/5.11.1/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/JoseCardenas/qt/5.11.1/clang_64/mkspecs/macx-clang -I/Users/JoseCardenas/nfl_project/project_2_NFL_jdaddy -I/Users/JoseCardenas/qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/JoseCardenas/qt/5.11.1/clang_64/lib/QtGui.framework/Headers -I/Users/JoseCardenas/qt/5.11.1/clang_64/lib/QtSql.framework/Headers -I/Users/JoseCardenas/qt/5.11.1/clang_64/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward -F/Users/JoseCardenas/qt/5.11.1/clang_64/lib traversalsummarywindow.h -o moc_traversalsummarywindow.cpp

moc_purchasewindow.cpp: ../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		team.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QString \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		stadium.h \
		souvenirmap.h \
		makeoutputmodel.h \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/QStandardItemModel \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		purchasewindow.h \
		moc_predefs.h \
		../../qt/5.11.1/clang_64/bin/moc
	/Users/JoseCardenas/qt/5.11.1/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/JoseCardenas/qt/5.11.1/clang_64/mkspecs/macx-clang -I/Users/JoseCardenas/nfl_project/project_2_NFL_jdaddy -I/Users/JoseCardenas/qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/JoseCardenas/qt/5.11.1/clang_64/lib/QtGui.framework/Headers -I/Users/JoseCardenas/qt/5.11.1/clang_64/lib/QtSql.framework/Headers -I/Users/JoseCardenas/qt/5.11.1/clang_64/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward -F/Users/JoseCardenas/qt/5.11.1/clang_64/lib purchasewindow.h -o moc_purchasewindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_adminwindow.h ui_summarywindow.h ui_traversalsummarywindow.h ui_purchasewindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_adminwindow.h ui_summarywindow.h ui_traversalsummarywindow.h ui_purchasewindow.h
ui_mainwindow.h: mainwindow.ui \
		../../qt/5.11.1/clang_64/bin/uic
	/Users/JoseCardenas/qt/5.11.1/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_adminwindow.h: adminwindow.ui \
		../../qt/5.11.1/clang_64/bin/uic
	/Users/JoseCardenas/qt/5.11.1/clang_64/bin/uic adminwindow.ui -o ui_adminwindow.h

ui_summarywindow.h: summarywindow.ui \
		../../qt/5.11.1/clang_64/bin/uic
	/Users/JoseCardenas/qt/5.11.1/clang_64/bin/uic summarywindow.ui -o ui_summarywindow.h

ui_traversalsummarywindow.h: traversalsummarywindow.ui \
		../../qt/5.11.1/clang_64/bin/uic
	/Users/JoseCardenas/qt/5.11.1/clang_64/bin/uic traversalsummarywindow.ui -o ui_traversalsummarywindow.h

ui_purchasewindow.h: purchasewindow.ui \
		../../qt/5.11.1/clang_64/bin/uic
	/Users/JoseCardenas/qt/5.11.1/clang_64/bin/uic purchasewindow.ui -o ui_purchasewindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		adminbackend.h \
		dbmanager.h \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QDir \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QString \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QFile \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/QtSql \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qtsqlglobal.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QVector \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qvector.h \
		team.h \
		stadium.h \
		makeoutputmodel.h \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/QStandardItemModel \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		souvenirmap.h \
		adminwindow.h \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QListWidgetItem \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qlistwidget.h \
		traversalsummarywindow.h \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		summarywindow.h \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/QPixmap \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		graph.h \
		purchasewindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		adminbackend.h \
		dbmanager.h \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QDir \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QString \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QFile \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/QtSql \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qtsqlglobal.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QVector \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qvector.h \
		team.h \
		stadium.h \
		makeoutputmodel.h \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/QStandardItemModel \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		souvenirmap.h \
		adminwindow.h \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QListWidgetItem \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qlistwidget.h \
		traversalsummarywindow.h \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		summarywindow.h \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/QPixmap \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		graph.h \
		purchasewindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

adminwindow.o: adminwindow.cpp adminwindow.h \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		makeoutputmodel.h \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/QStandardItemModel \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		stadium.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QString \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qstring.h \
		team.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		souvenirmap.h \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QListWidgetItem \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qlistwidget.h \
		ui_adminwindow.h \
		mainwindow.h \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		adminbackend.h \
		dbmanager.h \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QDir \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QFile \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/QtSql \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qtsqlglobal.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QVector \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qvector.h \
		traversalsummarywindow.h \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		summarywindow.h \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/QPixmap \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		graph.h \
		purchasewindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o adminwindow.o adminwindow.cpp

dbmanager.o: dbmanager.cpp dbmanager.h \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QDir \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QString \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QFile \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/QtSql \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qtsqlglobal.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QVector \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qvector.h \
		team.h \
		stadium.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dbmanager.o dbmanager.cpp

adminbackend.o: adminbackend.cpp adminbackend.h \
		dbmanager.h \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QDir \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QString \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QFile \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/QtSql \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qtsqlglobal.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QVector \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qvector.h \
		team.h \
		stadium.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o adminbackend.o adminbackend.cpp

team.o: team.cpp team.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QString \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		stadium.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o team.o team.cpp

stadium.o: stadium.cpp stadium.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QString \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qstring.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stadium.o stadium.cpp

makeoutputmodel.o: makeoutputmodel.cpp makeoutputmodel.h \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/QStandardItemModel \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		stadium.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QString \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qstring.h \
		team.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		souvenirmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o makeoutputmodel.o makeoutputmodel.cpp

graph.o: graph.cpp graph.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		team.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QString \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qstring.h \
		stadium.h \
		dbmanager.h \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QDir \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QFile \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/QtSql \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qtsqlglobal.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QVector \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qvector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graph.o graph.cpp

summarywindow.o: summarywindow.cpp summarywindow.h \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/QPixmap \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		dbmanager.h \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QDir \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QString \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QFile \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/QtSql \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qtsqlglobal.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../../qt/5.11.1/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QVector \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qvector.h \
		team.h \
		stadium.h \
		ui_summarywindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o summarywindow.o summarywindow.cpp

souvenirmap.o: souvenirmap.cpp souvenirmap.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QString \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o souvenirmap.o souvenirmap.cpp

traversalsummarywindow.o: traversalsummarywindow.cpp traversalsummarywindow.h \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/QStandardItemModel \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		ui_traversalsummarywindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o traversalsummarywindow.o traversalsummarywindow.cpp

purchasewindow.o: purchasewindow.cpp purchasewindow.h \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		team.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QString \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		stadium.h \
		souvenirmap.h \
		makeoutputmodel.h \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/QStandardItemModel \
		../../qt/5.11.1/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		ui_purchasewindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o purchasewindow.o purchasewindow.cpp

qrc_resource.o: qrc_resource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resource.o qrc_resource.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_adminwindow.o: moc_adminwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_adminwindow.o moc_adminwindow.cpp

moc_summarywindow.o: moc_summarywindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_summarywindow.o moc_summarywindow.cpp

moc_traversalsummarywindow.o: moc_traversalsummarywindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_traversalsummarywindow.o moc_traversalsummarywindow.cpp

moc_purchasewindow.o: moc_purchasewindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_purchasewindow.o moc_purchasewindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

